#!/usr/bin/env python3
"""Generate docs/jurnal/INDEX.md from curated knowledge base JSON."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
JURNAL = ROOT / "docs" / "jurnal"


def load_json(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def journal_exists(subdir: str, slug: str) -> str:
    p = JURNAL / subdir / f"{slug}.md"
    return "synced" if p.exists() else "pending"


def main() -> None:
    cats = load_json(DATA / "categories.json")["categories"]
    breeds: list[dict] = []
    for bf in sorted((DATA / "breeds").glob("*.json")):
        breeds.extend(load_json(bf).get("breeds", []))
    diseases: list[dict] = []
    for df in sorted((DATA / "clinical").glob("*.json")):
        diseases.extend(load_json(df).get("diseases", []))

    variant_count = sum(len(b.get("variants", [])) for b in breeds)

    lines = [
        "# Index Jurnal Perhewanan — Sobatpaws",
        "",
        f"> Auto-generated by `scripts/build_journal_index.py`. "
        f"**{len(cats)}** spesies · **{len(breeds)}** ras · "
        f"**{variant_count}** varian · **{len(diseases)}** penyakit (KB curated).",
        "",
        "## Statistik Dokumentasi",
        "",
        "| Kategori | KB | Jurnal | Coverage |",
        "|----------|-----|--------|----------|",
    ]

    spesies_done = sum(1 for c in cats if (JURNAL / "spesies" / f"{c['slug']}.md").exists())
    ras_done = sum(1 for b in breeds if (JURNAL / "ras" / f"{b['slug']}.md").exists())
    penyakit_done = sum(1 for d in diseases if (JURNAL / "penyakit" / f"{d['slug']}.md").exists())

    lines += [
        f"| Spesies | {len(cats)} | {spesies_done} | {spesies_done}/{len(cats)} |",
        f"| Ras | {len(breeds)} | {ras_done} | {ras_done}/{len(breeds)} |",
        f"| Varian (KB) | {variant_count} | — | lihat per ras |",
        f"| Penyakit | {len(diseases)} | {penyakit_done} | {penyakit_done}/{len(diseases)} |",
        "",
        "## Spesies",
        "",
        "| Slug | Nama | Kelas | Jurnal | Status |",
        "|------|------|-------|--------|--------|",
    ]
    for c in cats:
        slug = c["slug"]
        st = journal_exists("spesies", slug)
        link = f"[{slug}](spesies/{slug}.md)" if st == "synced" else "—"
        lines.append(
            f"| `{slug}` | {c['name_id']} | {c['species_class']} | {link} | {st} |"
        )

    lines += ["", "## Ras", "", "| Slug | Nama | Kategori | Varian | Jurnal |", "|------|------|----------|--------|--------|"]
    for b in sorted(breeds, key=lambda x: (x.get("category_slug", ""), x.get("name_id", ""))):
        slug = b["slug"]
        nvar = len(b.get("variants", []))
        st = journal_exists("ras", slug)
        link = f"[doc](ras/{slug}.md)" if st == "synced" else "—"
        lines.append(
            f"| `{slug}` | {b.get('name_id', b.get('name', ''))} | "
            f"{b.get('category_slug', '')} | {nvar} | {link} |"
        )

    lines += ["", "## Penyakit", "", "| Slug | Nama | Kategori | Darurat | Jurnal |", "|------|------|----------|---------|--------|"]
    for d in sorted(diseases, key=lambda x: x.get("slug", "")):
        slug = d["slug"]
        emerg = "ya" if d.get("is_emergency") else "tidak"
        st = journal_exists("penyakit", slug)
        link = f"[doc](penyakit/{slug}.md)" if st == "synced" else "—"
        lines.append(
            f"| `{slug}` | {d.get('name_id', d.get('name', ''))} | "
            f"{d.get('category_slug', '')} | {emerg} | {link} |"
        )

    lines += [
        "",
        "## Kesehatan Umum",
        "",
        "| Topik | File | Status |",
        "|-------|------|--------|",
        "| Vaksinasi anjing & kucing | [kesehatan/vaksinasi-dog-cat.md](kesehatan/vaksinasi-dog-cat.md) | draft |",
        "| Nutrisi hewan peliharaan | — | pending |",
        "| Parasit internal & eksternal | — | pending |",
        "",
        "## Backlog Riset (prioritas)",
        "",
        "1. Monograf ras prioritas (Golden Retriever, Persian, Holland Lop, dll.)",
        "2. Expand penyakit dari 30 → target 100+ per kategori utama",
        "3. Varian dengan implikasi klinis (brachycephalic, coat type)",
        "4. Sinkronisasi jurnal ↔ JSON setelah review architect",
        "",
    ]

    out = JURNAL / "INDEX.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out} ({len(cats)} species, {len(breeds)} breeds, {len(diseases)} diseases)")


if __name__ == "__main__":
    main()
