
import json, os, copy

CLINICAL = '/home/ubuntu/sobatpaws/data/clinical'

# Template-based disease generation for remaining slots
MORE_DISEASES = {
    "diseases_dogs.json": [
        {"slug": "dog-ccl-tear", "name": "Cranial Cruciate Ligament Tear", "name_id": "ACL Robek", "etiology": "traumatic", "body_system": "musculoskeletal", "is_contagious": False, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Robeknya ligamen krusiat di lutut.", "symptoms": [{"name": "Lameness", "name_id": "Pincang", "body_system": "musculoskeletal", "frequency": "very_high"}]},
        {"slug": "dog-atopic-dermatitis", "name": "Atopic Dermatitis", "name_id": "Dermatitis Atopik", "etiology": "allergic_immune", "body_system": "integumentary", "is_contagious": False, "is_zoonotic": False, "default_severity": "mild", "is_emergency": False, "overview": "Alergi kulit kronis terhadap allergen lingkungan.", "symptoms": [{"name": "Pruritus", "name_id": "Gatal", "body_system": "integumentary", "frequency": "very_high"}]},
        {"slug": "dog-leptospirosis", "name": "Leptospirosis", "name_id": "Leptospirosis", "etiology": "infectious_bacterial", "body_system": "systemic", "is_contagious": False, "is_zoonotic": True, "default_severity": "critical", "is_emergency": True, "overview": "Infeksi bakteri Leptospira yang menyerang ginjal dan hati.", "symptoms": [{"name": "Fever", "name_id": "Demam", "body_system": "systemic", "frequency": "very_high"}, {"name": "Jaundice", "name_id": "Kuning", "body_system": "systemic", "frequency": "high", "is_red_flag": True}]},
        {"slug": "dog-tick-fever", "name": "Ehrlichiosis", "name_id": "Tick Fever", "etiology": "parasitic", "body_system": "systemic", "is_contagious": False, "is_zoonotic": True, "default_severity": "moderate", "is_emergency": False, "overview": "Infeksi bakteri Ehrlichia melalui gigitan caplak.", "symptoms": [{"name": "Fever", "name_id": "Demam", "body_system": "systemic", "frequency": "very_high"}, {"name": "Lethargy", "name_id": "Lemas", "body_system": "systemic", "frequency": "very_high"}]},
        {"slug": "dog-anal-sac-impaction", "name": "Anal Sac Impaction", "name_id": "Kelenjar Anus Tersumbat", "etiology": "digestive_disorder", "body_system": "digestive", "is_contagious": False, "is_zoonotic": False, "default_severity": "mild", "is_emergency": False, "overview": "Kelenjar anal tidak bisa dikosongkan secara alami.", "symptoms": [{"name": "Scooting", "name_id": "Nyeret pantat", "body_system": "digestive", "frequency": "very_high"}]},
        {"slug": "dog-canine-cough", "name": "Kennel Cough", "name_id": "Batuk Kennel", "etiology": "infectious_bacterial", "body_system": "respiratory", "is_contagious": True, "is_zoonotic": False, "default_severity": "mild", "is_emergency": False, "overview": "Infeksi saluran pernapasan atas yang sangat menular.", "symptoms": [{"name": "Honking cough", "name_id": "Batuk bunyi klakson", "body_system": "respiratory", "frequency": "very_high"}]},
    ],
    "diseases_cats.json": [
        {"slug": "cat-panleukopenia", "name": "Feline Panleukopenia", "name_id": "Panleukopenia", "etiology": "infectious_viral", "body_system": "systemic", "is_contagious": True, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Penyakit virus parvo kucing yang sangat menular dan sering fatal.", "symptoms": [{"name": "Vomiting", "name_id": "Muntah", "body_system": "digestive", "frequency": "very_high"}, {"name": "Diarrhea", "name_id": "Diare", "body_system": "digestive", "frequency": "very_high"}]},
        {"slug": "cat-calicivirus", "name": "Feline Calicivirus", "name_id": "Calicivirus", "etiology": "infectious_viral", "body_system": "respiratory", "is_contagious": True, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Virus saluran pernapasan dengan ulserasi mulut.", "symptoms": [{"name": "Oral ulcers", "name_id": "Sariawan", "body_system": "dental", "frequency": "very_high"}, {"name": "Sneezing", "name_id": "Bersin", "body_system": "respiratory", "frequency": "high"}]},
        {"slug": "cat-herpesvirus", "name": "Feline Herpesvirus", "name_id": "Herpes Kucing", "etiology": "infectious_viral", "body_system": "respiratory", "is_contagious": True, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Penyebab utama flu kucing.", "symptoms": [{"name": "Conjunctivitis", "name_id": "Konjungtivitis", "body_system": "ocular", "frequency": "very_high"}, {"name": "Sneezing", "name_id": "Bersin", "body_system": "respiratory", "frequency": "very_high"}]},
        {"slug": "cat-felv", "name": "Feline Leukemia Virus", "name_id": "FeLV", "etiology": "infectious_viral", "body_system": "immune", "is_contagious": True, "is_zoonotic": False, "default_severity": "chronic", "is_emergency": False, "overview": "Virus imunosupresif penyebab kanker dan infeksi sekunder.", "symptoms": [{"name": "Weight loss", "name_id": "BB turun", "body_system": "systemic", "frequency": "very_high"}, {"name": "Pale gums", "name_id": "Gusi pucat", "body_system": "systemic", "frequency": "high", "is_red_flag": True}]},
        {"slug": "cat-cystitis", "name": "Feline Idiopathic Cystitis", "name_id": "FIC (Radang Kandung Kemih)", "etiology": "idiopathic", "body_system": "urinary", "is_contagious": False, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Radang kandung kemih tanpa penyebab jelas, terkait stres.", "symptoms": [{"name": "Straining to urinate", "name_id": "Ngeden kencing", "body_system": "urinary", "frequency": "very_high"}, {"name": "Blood in urine", "name_id": "Kencing darah", "body_system": "urinary", "frequency": "high", "is_red_flag": True}]},
        {"slug": "cat-urinary-blockage", "name": "Feline Urethral Obstruction", "name_id": "Sumbatan Kencing", "etiology": "metabolic_nutritional", "body_system": "urinary", "is_contagious": False, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Kondisi darurat dimana uretra tersumbat.", "symptoms": [{"name": "Straining", "name_id": "Ngeden", "body_system": "urinary", "frequency": "very_high", "is_red_flag": True}]},
        {"slug": "cat-tooth-resorption", "name": "Feline Tooth Resorption", "name_id": "Resorpsi Gigi", "etiology": "degenerative", "body_system": "dental", "is_contagious": False, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Kerusakan gigi progresif pada kucing.", "symptoms": [{"name": "Drooling", "name_id": "Ngeces", "body_system": "dental", "frequency": "very_high"}, {"name": "Difficulty eating", "name_id": "Susah makan", "body_system": "dental", "frequency": "high"}]},
    ],
    "diseases_rabbits.json": [
        {"slug": "rabbit-uterine-adenocarcinoma", "name": "Uterine Adenocarcinoma", "name_id": "Kanker Rahim", "etiology": "neoplastic", "body_system": "reproductive", "is_contagious": False, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Kanker rahim pada kelinci betina yang tidak disteril.", "symptoms": [{"name": "Bloody discharge", "name_id": "Keluaran darah", "body_system": "reproductive", "frequency": "high", "is_red_flag": True}]},
        {"slug": "rabbit-head-tilt", "name": "Head Tilt (Torticollis)", "name_id": "Miring Kepala", "etiology": "infectious_bacterial", "body_system": "neurological", "is_contagious": False, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Infeksi telinga dalam yang menyebabkan kepala miring.", "symptoms": [{"name": "Head tilt", "name_id": "Kepala miring", "body_system": "neurological", "frequency": "very_high", "is_red_flag": True}]},
        {"slug": "rabbit-fly-strike", "name": "Fly Strike (Myiasis)", "name_id": "Belatungan", "etiology": "parasitic", "body_system": "integumentary", "is_contagious": False, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Lalat bertelur di area kotor dan menetas jadi belatung.", "symptoms": [{"name": "Maggots visible", "name_id": "Ada belatung", "body_system": "integumentary", "frequency": "very_high", "is_red_flag": True}]},
    ],
    "diseases_fish.json": [
        {"slug": "fish-ich", "name": "Ichthyophthirius (White Spot)", "name_id": "Bintik Putih", "etiology": "parasitic", "body_system": "integumentary", "is_contagious": True, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Parasit protozoa penyebab bintik putih pada ikan.", "symptoms": [{"name": "White spots", "name_id": "Bintik putih", "body_system": "integumentary", "frequency": "very_high"}]},
        {"slug": "fish-fin-rot", "name": "Fin Rot", "name_id": "Busuk Sirip", "etiology": "infectious_bacterial", "body_system": "integumentary", "is_contagious": True, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Infeksi bakteri yang mengikis sirip ikan.", "symptoms": [{"name": "Ragged fins", "name_id": "Sirip robek", "body_system": "integumentary", "frequency": "very_high"}]},
        {"slug": "fish-dropsy", "name": "Dropsy", "name_id": "Dropsy", "etiology": "infectious_bacterial", "body_system": "systemic", "is_contagious": True, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Penumpukan cairan di rongga tubuh akibat gagal organ.", "symptoms": [{"name": "Pinecone scales", "name_id": "Sisik mengembang", "body_system": "integumentary", "frequency": "very_high", "is_red_flag": True}]},
        {"slug": "fish-swim-bladder", "name": "Swim Bladder Disorder", "name_id": "Gangguan Gelembung Renang", "etiology": "digestive_disorder", "body_system": "digestive", "is_contagious": False, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Masalah keseimbangan akibat gangguan gelembung renang.", "symptoms": [{"name": "Floating upside down", "name_id": "Terapung terbalik", "body_system": "musculoskeletal", "frequency": "very_high"}]},
        {"slug": "fish-columnaris", "name": "Columnaris (Cotton Wool)", "name_id": "Columnaris", "etiology": "infectious_bacterial", "body_system": "integumentary", "is_contagious": True, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Infeksi bakteri Flavobacterium pada mulut dan sirip.", "symptoms": [{"name": "Cotton-like patches", "name_id": "Bercak kapas", "body_system": "integumentary", "frequency": "very_high"}]},
    ],
    "diseases_reptiles.json": [
        {"slug": "reptile-mbd", "name": "Metabolic Bone Disease", "name_id": "Penyakit Tulang Metabolik", "etiology": "metabolic_nutritional", "body_system": "musculoskeletal", "is_contagious": False, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Defisiensi kalsium dan vitamin D3 pada reptil.", "symptoms": [{"name": "Soft jaw", "name_id": "Rahang lunak", "body_system": "musculoskeletal", "frequency": "very_high", "is_red_flag": True}]},
        {"slug": "reptile-rti", "name": "Respiratory Tract Infection", "name_id": "Infeksi Saluran Napas", "etiology": "infectious_bacterial", "body_system": "respiratory", "is_contagious": True, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Infeksi saluran napas akibat suhu/kelembaban tidak sesuai.", "symptoms": [{"name": "Open mouth breathing", "name_id": "Napas buka mulut", "body_system": "respiratory", "frequency": "very_high"}]},
        {"slug": "reptile-mites", "name": "Mite Infestation", "name_id": "Kutu Reptil", "etiology": "parasitic", "body_system": "integumentary", "is_contagious": True, "is_zoonotic": False, "default_severity": "mild", "is_emergency": False, "overview": "Infestasi tungau pada kulit reptil.", "symptoms": [{"name": "Visible mites", "name_id": "Tungau terlihat", "body_system": "integumentary", "frequency": "very_high"}]},
        {"slug": "reptile-dysecdysis", "name": "Dysecdysis (Shedding Problems)", "name_id": "Gagal Ganti Kulit", "etiology": "metabolic_nutritional", "body_system": "integumentary", "is_contagious": False, "is_zoonotic": False, "default_severity": "mild", "is_emergency": False, "overview": "Kesulitan melepas kulit lama.", "symptoms": [{"name": "Retained shed", "name_id": "Kulit lama menempel", "body_system": "integumentary", "frequency": "very_high"}]},
        {"slug": "reptile-stomatitis", "name": "Stomatitis (Mouth Rot)", "name_id": "Busuk Mulut", "etiology": "infectious_bacterial", "body_system": "dental", "is_contagious": True, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Infeksi mulut pada reptil.", "symptoms": [{"name": "Excessive saliva", "name_id": "Ludah berlebih", "body_system": "dental", "frequency": "very_high"}]},
    ],
    "diseases_amphibian.json": [
        {"slug": "amphibian-chytrid", "name": "Chytridiomycosis", "name_id": "Chytrid", "etiology": "infectious_fungal", "body_system": "integumentary", "is_contagious": True, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Infeksi jamur Batrachochytrium penyebab kepunahan amfibi global.", "symptoms": [{"name": "Excessive shedding", "name_id": "Kulit mengelupas", "body_system": "integumentary", "frequency": "very_high", "is_red_flag": True}]},
        {"slug": "amphibian-red-leg", "name": "Red Leg Syndrome", "name_id": "Red Leg", "etiology": "infectious_bacterial", "body_system": "systemic", "is_contagious": True, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Infeksi bakteri sistemik pada katak.", "symptoms": [{"name": "Red thighs", "name_id": "Paha merah", "body_system": "integumentary", "frequency": "very_high", "is_red_flag": True}]},
    ],
    "diseases_poultry.json": [
        {"slug": "poultry-avian-flu", "name": "Avian Influenza", "name_id": "Flu Burung", "etiology": "infectious_viral", "body_system": "respiratory", "is_contagious": True, "is_zoonotic": True, "default_severity": "critical", "is_emergency": True, "overview": "Penyakit viral zoonotik pada unggas. WAJIB LAPOR!", "symptoms": [{"name": "Sudden death", "name_id": "Mati mendadak", "body_system": "systemic", "frequency": "very_high", "is_red_flag": True}]},
        {"slug": "poultry-newcastle", "name": "Newcastle Disease", "name_id": "Tetelo", "etiology": "infectious_viral", "body_system": "respiratory", "is_contagious": True, "is_zoonotic": True, "default_severity": "critical", "is_emergency": True, "overview": "Penyakit viral sangat menular pada unggas.", "symptoms": [{"name": "Respiratory distress", "name_id": "Sesak napas", "body_system": "respiratory", "frequency": "very_high"}]},
        {"slug": "poultry-coccidiosis", "name": "Coccidiosis", "name_id": "Koksidiosis", "etiology": "parasitic", "body_system": "digestive", "is_contagious": True, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Infeksi protozoa Eimeria pada usus unggas.", "symptoms": [{"name": "Bloody diarrhea", "name_id": "Diare darah", "body_system": "digestive", "frequency": "very_high"}]},
        {"slug": "poultry-marek", "name": "Marek's Disease", "name_id": "Marek", "etiology": "infectious_viral", "body_system": "neurological", "is_contagious": True, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Virus herpes penyebab tumor dan kelumpuhan pada ayam.", "symptoms": [{"name": "Paralysis", "name_id": "Lumpuh", "body_system": "neurological", "frequency": "very_high", "is_red_flag": True}]},
        {"slug": "poultry-egg-binding", "name": "Egg Binding", "name_id": "Telur Nyangkut", "etiology": "digestive_disorder", "body_system": "reproductive", "is_contagious": False, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Telur tidak bisa dikeluarkan.", "symptoms": [{"name": "Straining", "name_id": "Ngeden", "body_system": "reproductive", "frequency": "very_high", "is_red_flag": True}]},
    ],
    "diseases_hamsters.json": [
        {"slug": "hamster-wet-tail", "name": "Wet Tail (Proliferative Ileitis)", "name_id": "Ekor Basah", "etiology": "infectious_bacterial", "body_system": "digestive", "is_contagious": True, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Penyakit diare akut pada hamster muda.", "symptoms": [{"name": "Watery diarrhea", "name_id": "Diare cair", "body_system": "digestive", "frequency": "very_high", "is_red_flag": True}]},
        {"slug": "hamster-cheek-pouch", "name": "Cheek Pouch Impaction", "name_id": "Kantong Pipi Tersumbat", "etiology": "digestive_disorder", "body_system": "digestive", "is_contagious": False, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Makanan tersangkut di kantong pipi.", "symptoms": [{"name": "Swollen cheek", "name_id": "Pipi bengkak", "body_system": "digestive", "frequency": "very_high"}]},
    ],
    "diseases_guinea_pig.json": [
        {"slug": "guinea-scurvy", "name": "Scurvy (Vitamin C Deficiency)", "name_id": "Scorbut", "etiology": "metabolic_nutritional", "body_system": "systemic", "is_contagious": False, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Defisiensi vitamin C pada marmut.", "symptoms": [{"name": "Joint pain", "name_id": "Nyeri sendi", "body_system": "musculoskeletal", "frequency": "very_high"}]},
        {"slug": "guinea-URI", "name": "Upper Respiratory Infection", "name_id": "Infeksi Saluran Napas Atas", "etiology": "infectious_bacterial", "body_system": "respiratory", "is_contagious": True, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Infeksi saluran napas yang cepat memburuk pada marmut.", "symptoms": [{"name": "Sneezing", "name_id": "Bersin", "body_system": "respiratory", "frequency": "very_high"}, {"name": "Eye discharge", "name_id": "Mata belekan", "body_system": "ocular", "frequency": "high"}]},
        {"slug": "guinea-bumblefoot", "name": "Bumblefoot (Pododermatitis)", "name_id": "Pododermatitis", "etiology": "infectious_bacterial", "body_system": "musculoskeletal", "is_contagious": False, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Infeksi telapak kaki pada marmut.", "symptoms": [{"name": "Swollen feet", "name_id": "Kaki bengkak", "body_system": "musculoskeletal", "frequency": "very_high"}]},
    ],
    "diseases_ferret.json": [
        {"slug": "ferret-adrenal", "name": "Adrenal Gland Disease", "name_id": "Penyakit Adrenal", "etiology": "neoplastic", "body_system": "endocrine", "is_contagious": False, "is_zoonotic": False, "default_severity": "moderate", "is_emergency": False, "overview": "Tumor kelenjar adrenal pada musang.", "symptoms": [{"name": "Hair loss", "name_id": "Rontok bulu", "body_system": "integumentary", "frequency": "very_high"}]},
        {"slug": "ferret-insulinoma", "name": "Insulinoma", "name_id": "Insulinoma", "etiology": "neoplastic", "body_system": "endocrine", "is_contagious": False, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Tumor pankreas penghasil insulin berlebih.", "symptoms": [{"name": "Lethargy", "name_id": "Lemas", "body_system": "systemic", "frequency": "very_high"}, {"name": "Stargazing", "name_id": "Menatap kosong", "body_system": "neurological", "frequency": "high", "is_red_flag": True}]},
    ],
    "diseases_exotic_others.json": [
        {"slug": "hedgehog-wobbly", "name": "Wobbly Hedgehog Syndrome", "name_id": "WHS", "etiology": "degenerative", "body_system": "neurological", "is_contagious": False, "is_zoonotic": False, "default_severity": "chronic", "is_emergency": False, "overview": "Penyakit neurologis degeneratif pada landak.", "symptoms": [{"name": "Ataxia", "name_id": "Jalan sempoyongan", "body_system": "neurological", "frequency": "very_high"}]},
        {"slug": "hedgehog-mites", "name": "Mange (Mite Infestation)", "name_id": "Kurap Landak", "etiology": "parasitic", "body_system": "integumentary", "is_contagious": True, "is_zoonotic": True, "default_severity": "moderate", "is_emergency": False, "overview": "Infestasi tungau penyebab keropeng dan rontok duri.", "symptoms": [{"name": "Quill loss", "name_id": "Duri rontok", "body_system": "integumentary", "frequency": "very_high"}]},
        {"slug": "sugar-glider-nutritional", "name": "Nutritional Osteodystrophy", "name_id": "Penyakit Tulang Metabolik", "etiology": "metabolic_nutritional", "body_system": "musculoskeletal", "is_contagious": False, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Defisiensi kalsium pada kuskus gula.", "symptoms": [{"name": "Tremors", "name_id": "Tremor", "body_system": "neurological", "frequency": "very_high", "is_red_flag": True}]},
        {"slug": "chinchilla-heat-stroke", "name": "Heat Stroke", "name_id": "Heat Stroke", "etiology": "traumatic", "body_system": "systemic", "is_contagious": False, "is_zoonotic": False, "default_severity": "critical", "is_emergency": True, "overview": "Suhu tubuh naik drastis pada chinchilla yang sensitif panas.", "symptoms": [{"name": "Lethargy", "name_id": "Lemas", "body_system": "systemic", "frequency": "very_high"}, {"name": "Red ears", "name_id": "Telinga merah", "body_system": "systemic", "frequency": "high", "is_red_flag": True}]},
        {"slug": "chinchilla-fur-chewing", "name": "Fur Chewing", "name_id": "Kunyah Bulu", "etiology": "behavioral", "body_system": "behavioral", "is_contagious": False, "is_zoonotic": False, "default_severity": "mild", "is_emergency": False, "overview": "Perilaku mencabut bulu akibat stres atau bosan.", "symptoms": [{"name": "Patchy fur", "name_id": "Bulu botak", "body_system": "integumentary", "frequency": "very_high"}]},
    ],
}

total_added = 0
for fname, new_diseases in MORE_DISEASES.items():
    fpath = os.path.join(CLINICAL, fname)
    with open(fpath) as f:
        data = json.load(f)
    existing = data.get('diseases', [])
    existing_slugs = {d['slug'] for d in existing}
    added = 0
    for d in new_diseases:
        if d['slug'] not in existing_slugs:
            existing.append(d)
            added += 1
            existing_slugs.add(d['slug'])
    data['diseases'] = existing
    with open(fpath, 'w') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    total_added += added
    print(f"{fname}: {len(existing)} diseases (+{added})")

total = sum(len(json.load(open(os.path.join(CLINICAL, f)))['diseases']) for f in os.listdir(CLINICAL) if f.startswith('diseases_'))
print(f"\n=== FINAL: {total} total diseases (+{total_added} new) ===")
